Update to latest MobileCoin and Ledger SDKs (replaces #18)
LedgerHQ/app-mobilecoin pull request #19
Opened 2024-08-12 22:19 UTC by ryankurte

# Changes

- Updates rust toolchain + Ledger SDK to `1.14.0` (from upstream)
- Updates manifests for `cargo-ledger`, tooling to use this where possible
- Updates MobileCoin SDK to `6.0.0`
- Adds a test vector for block version 4
- Minor formatting changes to appease updated clippy/rustfmt

# Checklist

- [ ] App update process has been followed 
- [x] Target branch is `develop` 
- [ ] Application version has been bumped

2024-08-29 13:15 UTC, yogh333 requested changes

2024-08-29 13:15 UTC, yogh333 commented on .github/workflows/rust.yml
> +        toolchain: nightly-2023-10-01
We are using nightly-2023-11-10 when building your app for prod. I think you should use the same nightly version

2024-08-29 13:15 UTC, yogh333 commented on fw/Cargo.toml
> +api_level = "5"
No more needed

2024-08-29 13:15 UTC, yogh333 commented on fw/Cargo.toml
> +#ledger_secure_sdk_sys = { path = "../../ledger-device-rust-sdk/ledger_secure_sdk_sys" }
you should delete those two lines

2024-08-29 13:15 UTC, yogh333 commented on fw/rust-toolchain
I think this file should be deleted to prevent any nightly version override

2024-08-29 13:15 UTC, yogh333 commented on rust-toolchain
Please delete this file

2024-08-29 23:01 UTC, ryankurte commented on fw/rust-toolchain
we can remove these if it's really important, however, if we do there is no way to control what rust version the app is compiled or tested with during local development (a problem for those of us who use different toolchains for different tasks) :-/

2024-08-30 08:07 UTC, yogh333 commented on fw/rust-toolchain
Regarding the Rust toolchain, our recommendation is to use our Docker containers ([here](https://github.com/LedgerHQ/ledger-app-builder)) to develop and build any Rust app for our devices: [full](https://github.com/LedgerHQ/ledger-app-builder/tree/master/full) embeds proper C and Rust toolchains, along with [cargo-ledger](https://github.com/LedgerHQ/ledger-device-rust-sdk/tree/master/cargo-ledger) tool, all of them being used internally when building and deploying apps, and [dev-tools](https://github.com/LedgerHQ/ledger-app-builder/tree/master/dev-tools) embeds additional testing tools (speculos, ragger). By using both the docker containers and cargo-ledger, you are sure that you develop with the same env and toolchains as the ones we use when deploying your app.
Additionally, regarding the CI, we also propose some [workflows](https://developers.ledger.com/docs/device-app/develop/tools#github-workflows), some of them being mandatory nowadays.
We do not prevent to use local development but in that case, you should stick as much as possible to our tools to prevent any issue when your app will be deployed in prod.
So as a first step, I would highly recommend to align at least the Rust toolchain with ours (**nightly-2023-11-10**).
For next future steps (future PRs, it could be part of Stax/Flex porting job also), using our dev environment (i.e. our docker containers), tools (cargo-ledger) and CI workflows should be taken into account (see [here](https://developers.ledger.com/docs/device-app/develop/requirements/development) and [here](https://developers.ledger.com/docs/device-app/develop/tools)). We will support you if you have any questions/issues.
Thanks !

2024-08-30 22:41 UTC, holtzman commented on fw/rust-toolchain
thanks @yogh333 for the excellent pointers to the official build and dev containers.

we've already done the first step that you recommend -- rust.yml has been updated throughout to use nightly-2023-11-10 and we also already updated rust-toolchain and fw/rust-toolchain to use nightly-2023-11-10.  We'll work on further harmonizing as you recommend for our next PR.

Have we missed anything for getting this PR merged and 0.16.2 released?

Thanks again!

2024-08-30 22:43 UTC, holtzman commented on rust-toolchain
See conversation under fw/rust-toolchain.  TL; DR: We've updated to nightly-2023-11-10 and will work on harmonizing our dev environment to delete this file as part of a future PR 

Thanks!

2024-09-02 07:31 UTC, yogh333 approved these changes

2024-09-02 07:52 UTC, merged